"""empty message

Revision ID: 95baf3659b89
Revises: 89b0f4b4176c
Create Date: 2021-06-29 02:45:07.327551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95baf3659b89'
down_revision = '89b0f4b4176c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['board_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'board_id')
    # ### end Alembic commands ###
